import {
  Package,
  Users2,
  Factory,
  Cog,
  Route as RouteIcon,
  AlertTriangle,
  Award,
  Palette,
  Sparkles,
  Tag,
  Building2,
  Settings2,
  Tags,
  Tablet,
  CalendarClock,
  type LucideIcon,
} from "lucide-react";
import type { DefinitionGroupKey } from "./groups-config";

export interface DefinitionTile {
  key: string;
  title: string;
  description: string;
  icon: LucideIcon;
  to: string;
  group: DefinitionGroupKey;
  permission?: string;
}

export const definitionTiles: DefinitionTile[] = [
  {
    key: "items",
    title: "Ürünler",
    description: "Stok kalemleri ve varyantlar",
    icon: Package,
    to: "/definitions/items",
    group: "catalog",
    permission: "item:read",
  },
  {
    key: "fabric-properties",
    title: "Kumaş Özellikleri",
    description: "Yanmazlık, su geçirmezlik gibi kazanımlar",
    icon: Sparkles,
    to: "/definitions/fabric-properties",
    group: "catalog",
    permission: "property:read",
  },
  {
    key: "colors",
    title: "Renkler",
    description: "Boyahane renk kataloğu",
    icon: Palette,
    to: "/definitions/colors",
    group: "catalog",
    permission: "item:read",
  },
  {
    key: "quality-grades",
    title: "Kalite Sınıfları",
    description: "Sistem sabit kalite kademeleri (salt okunur)",
    icon: Award,
    to: "/definitions/quality-grades",
    group: "catalog",
    permission: "quality:read",
  },
  {
    key: "customers",
    title: "Müşteriler",
    description: "Müşteri ve tedarikçi firmalar",
    icon: Users2,
    to: "/definitions/customers",
    group: "partners",
    permission: "customer:read",
  },
  {
    key: "subcontractors",
    title: "Fason Firmalar",
    description: "Dış hizmet sağlayan firmalar ve verdikleri hizmetler",
    icon: Building2,
    to: "/definitions/subcontractors",
    group: "partners",
    permission: "subcontractor:read",
  },
  {
    key: "subcontractor-categories",
    title: "Fason Kategorileri",
    description: "Boyahane, baskı, yıkama gibi hizmet türleri",
    icon: Tag,
    to: "/definitions/subcontractor-categories",
    group: "partners",
    permission: "subcontractor:read",
  },
  {
    key: "stations",
    title: "İstasyonlar",
    description: "Üretim istasyonları ve fason birimleri",
    icon: Factory,
    to: "/definitions/stations",
    group: "production",
    permission: "station:read",
  },
  {
    key: "machines",
    title: "Makineler",
    description: "İstasyonlardaki makine envanteri",
    icon: Cog,
    to: "/definitions/machines",
    group: "production",
    permission: "station:read",
  },
  {
    key: "station-capabilities",
    title: "İstasyon Yetenekleri",
    description: "Fason istasyonlarının uygulayabileceği renk ve özellikler",
    icon: Settings2,
    to: "/definitions/station-capabilities",
    group: "production",
    permission: "station:read",
  },
  {
    key: "routes",
    title: "Üretim Rotaları",
    description: "Şablon iş akışları ve istasyon sıraları",
    icon: RouteIcon,
    to: "/definitions/routes",
    group: "production",
    permission: "station:read",
  },
  {
    key: "defect-types",
    title: "Hata Tipleri",
    description: "Kalite kontrol hata tanımları",
    icon: AlertTriangle,
    to: "/definitions/defect-types",
    group: "production",
    permission: "quality:read",
  },
  {
    key: "deadline-defaults",
    title: "Termin Varsayılanları",
    description: "Sipariş ve iş emri açılışında otomatik atanan termin günleri",
    icon: CalendarClock,
    to: "/definitions/deadline-defaults",
    group: "system",
    permission: "admin:settings",
  },
  {
    key: "label-templates",
    title: "Etiket Standartları",
    description: "Top ve kartela etiketleri için alan listesi ve görünüm",
    icon: Tags,
    to: "/definitions/label-templates",
    group: "system",
    permission: "label-template:read",
  },
  {
    key: "devices",
    title: "Cihazlar",
    description: "Sahadaki tabletler ve hangi makineye eşli oldukları",
    icon: Tablet,
    to: "/definitions/devices",
    group: "system",
    permission: "admin:settings",
  },
];
