// =============================================================================
// AUDIT ALAN ETİKETLERİ — backend haritasının İSTEMCİ AYNASI
// =============================================================================
// ⚠️ AYNA: kaynak `Teks-Erp/src/constants/audit-field-labels.ts`. Electron
// backend'i import edemez (mobil `permissions.ts` ile aynı durum).
//
// ⚠️ BU DOSYA ELLE DÜZENLENMEZ — kaynaktaki `AUDIT_FIELD_LABELS` bloğu buraya
// BİREBİR kopyalanır. `Teks-Erp/scripts/test_audit_labels.ts` iki haritanın
// eşitliğini MEKANİK doğrular ve ayrışma KIRMIZI verir. Gerekçe: eski ayna
// 57 anahtarda donmuştu, kaynak 81'e çıkmıştı ve fark hiçbir yerde görünmüyordu
// (uyaran bekçi hiç yazılmamıştı — `AUDIT_FIELD_LABEL_KEYS` export'u kimse
// tarafından import edilmiyordu). Kapsam hâlâ FAIL-OPEN'dır: etiketi olmayan
// alan HAM ADIYLA basılır, ekran asla boş kalmaz.
// =============================================================================

export const AUDIT_FIELD_LABELS: Readonly<Record<string, string>> = {
  // ── Ortak / künye ──────────────────────────────────────────────────────────
  id: "Kayıt no",
  name: "Ad",
  code: "Kod",
  isActive: "Aktif",
  notes: "Not",
  description: "Açıklama",
  reason: "Gerekçe",
  reasonCode: "Gerekçe kodu",
  reasonId: "Gerekçe",
  kind: "Tür",
  category: "Kategori",
  categoryIds: "Kategoriler",
  sortOrder: "Sıra",
  isFavorite: "Sık kullanılan",
  isDefault: "Varsayılan",
  value: "Değer",
  message: "Mesaj",
  instruction: "Talimat",
  version: "Sürüm",
  createdAt: "Oluşturulma",
  updatedAt: "Güncellenme",
  deletedAt: "Silinme",
  createdById: "Oluşturan",
  updatedById: "Güncelleyen",
  nameFold: "Ad (arama karşılığı)",
  clientToken: "İstemci anahtarı",
  idempotentReplay: "Tekrar gönderim (aynı kayıt)",
  simulate: "Deneme (yazmadan)",
  warnings: "Uyarılar",
  source: "Kaynak",
  via: "Kapanış yolu",
  method: "HTTP metodu",
  path: "Adres",
  statusCode: "HTTP kodu",
  stack: "Hata yığını",
  errorType: "Hata türü",
  errorCount: "Hata sayısı",
  action: "İşlem",
  actions: "İşlemler",
  fields: "Alanlar",
  fieldsChanged: "Değişen alanlar",
  fieldCount: "Değişen alan sayısı",
  file: "Dosya",
  from: "Önce",
  to: "Sonra",

  // ── Top / üretim ───────────────────────────────────────────────────────────
  width: "En",
  currentQty: "Metraj",
  initialQty: "Giriş metrajı",
  weightKg: "Ağırlık (kg)",
  qty: "Metraj",
  qtyIn: "Giren metraj",
  totalQty: "Toplam metraj",
  totalMeters: "Toplam metraj",
  lengthMeters: "Metraj",
  cutLength: "Kesim boyu",
  startMeter: "Başlangıç metresi",
  lineStepMm: "Satır aralığı (mm)",
  status: "Durum",
  appliedStatus: "Uygulanan durum",
  form: "Biçim",
  qualityGrade: "Kalite",
  qualityGradeId: "Kalite",
  foldType: "Kat",
  barcode: "Barkod",
  parentBarcode: "Kaynak top barkodu",
  cardNumber: "Kart no",
  cardBarcode: "Kart barkodu",
  colorId: "Renk",
  colorIds: "Renkler",
  colorName: "Renk adı",
  color: "Renk",
  hex: "Renk (hex)",
  itemId: "Kumaş",
  itemType: "Kumaş türü",
  unit: "Birim",
  decimals: "Ondalık basamak",
  entrySource: "Giriş kaynağı",
  entryReason: "Ekleme nedeni",
  entryReasonCode: "Ekleme nedeni (kod)",
  cancelReasonCode: "İptal sebebi (kod)",
  declaredEnteredAt: "Operatörün girdiği saat",
  clientEnteredAt: "Cihazdaki kayıt saati",
  finalizedAt: "Üretim tamamlanma",
  propertyIds: "Özellikler",
  appliedPropertyIds: "Uygulanan özellikler",
  appliedColorId: "Uygulanan renk",
  appliedWidth: "Uygulanan en",
  allowedColorIds: "İzin verilen renkler",
  allowedPropertyIds: "İzin verilen özellikler",
  rollIds: "Toplar",
  rollCount: "Top adedi",
  consumedRollCount: "Kapanan top adedi",
  restoredRolls: "Geri alınan toplar",
  restoredQty: "Geri alınan metraj",
  restoredLen: "Geri alınan metraj",
  restoredTo: "Geri alındığı durum",
  canRestore: "Geri alınabilir",
  cancelled: "İptal edildi",
  created: "Oluşturulan",
  totalCreated: "Oluşturulan adet",
  insertedCount: "Eklenen adet",
  closedCount: "Kapatılan adet",
  rolledBackRollCount: "Geri alınan top adedi",
  dispositionCount: "Karar verilen top adedi",
  autoAttachedRollCount: "Kendiliğinden bağlanan top adedi",
  moved: "Taşınan",
  adopted: "Devralınan",
  reassigned: "Yeniden atanan",
  reactivated: "Yeniden aktifleştirilen",
  markedForKartela: "Kartelalık işaretlendi",
  labelPrinted: "Etiket basıldı",

  // ── Tambur: kesim, bölme, geri alma ────────────────────────────────────────
  parentRollId: "Kaynak top",
  parentOpenFabricId: "Kaynak açık kumaş",
  parentRemainingQty: "Kaynakta kalan metraj",
  parentReceiptId: "Kaynak makbuz",
  childBarcode: "Alt top barkodu",
  childStatus: "Alt top durumu",
  childQualityGrade: "Alt top kalitesi",
  cancelledChildId: "İptal edilen alt top",
  cancelledChildIds: "İptal edilen alt toplar",
  cancelledChildBarcode: "İptal edilen alt top barkodu",
  remainingAction: "Kalan için karar",
  remainingQty: "Kalan metraj",
  remainingChildId: "Kalan parça",
  remainingChildQuality: "Kalan parçanın kalitesi",
  rotated: "Döndürüldü",
  propsRestored: "Özellikler geri alındı",
  reopenedErrors: "Yeniden açılan hatalar",
  reopened: "Yeniden açıldı",

  // ── İş emri / adım ─────────────────────────────────────────────────────────
  workOrderNumber: "İş emri no",
  workOrderStepId: "İş emri adımı",
  targetQuantity: "Hedef metraj",
  targetWeight: "Hedef ağırlık",
  targetItemId: "Hedef kumaş",
  targetColorId: "Hedef renk",
  targetPropertyIds: "Hedef özellikler",
  synthesizedColorId: "Türetilen renk",
  synthColorRollIds: "Rengi türetilen toplar",
  routeTemplateId: "Rota şablonu",
  routeSkipOverride: "Rota dışına çıkma onayı",
  itemMismatchOverride: "Kumaş uyumsuzluğu onayı",
  plannedStartDate: "Planlanan başlangıç",
  plannedEndDate: "Planlanan bitiş",
  deadline: "Termin",
  type: "Tür",
  cancelReason: "İptal sebebi",
  stepId: "Adım",
  nextStepId: "Sonraki adım",
  targetStepId: "Hedef adım",
  targetStepName: "Hedef adım",
  currentStepId: "Bulunduğu adım",
  firstStepId: "İlk adım",
  tamburStepId: "Tambur adımı",
  stepCount: "Adım sayısı",
  skippedStepIds: "Atlanan adımlar",
  isLastStep: "Son adım",
  backflush: "Atlanan adımlar kapatıldı",
  qcBypassed: "Kalite adımı atlandı",
  qcVoided: "Kalite kararı iptal edildi",
  kursunFinished: "Kurşun kapatıldı",
  manualComplete: "Elle tamamlandı",
  completedVia: "Tamamlanma yolu",
  warehouseClosure: "Depoya alınarak kapatıldı",
  woRevived: "İş emri yeniden açıldı",
  producedInStepId: "Üretildiği adım",
  plannedSubcontractorId: "Planlanan fason firma",
  partyMode: "Parti kuralı",
  joinBatchId: "Bağlanan parti",
  newBatchNumber: "Yeni parti no",
  followUpBatchNumber: "Devam partisi no",

  // ── Sipariş ────────────────────────────────────────────────────────────────
  orderNumber: "Sipariş no",
  customerId: "Müşteri",
  branchId: "Şube",
  quantity: "Miktar",
  dueDate: "Termin",
  customerItemName: "Müşterideki kumaş adı",
  customerColorName: "Müşterideki renk adı",
  alias: "Müşterideki ad",
  lines: "Kalemler",
  linesCount: "Kalem sayısı",
  orderIds: "Siparişler",
  orderLineIds: "Sipariş kalemleri",
  linkedOrders: "Bağlanan siparişler",
  affectedOrders: "Etkilenen siparişler",
  alreadyLinked: "Zaten bağlı",
  totalAmount: "Toplam tutar",

  // ── Sevkiyat / çuval ───────────────────────────────────────────────────────
  shipmentNo: "Sevkiyat no",
  sackNo: "Çuval no",
  sackIds: "Çuvallar",
  targetSackId: "Hedef çuval",
  sackCount: "Çuval adedi",
  swatchCount: "Kartela adedi",
  destination: "Sevk yönü",
  rawDestination: "Sevk yönü (ham)",
  invoiceNo: "Fatura no",
  procedureCode: "İhracat kodu",
  exportCode: "İhracat kodu",
  documentNo: "Belge no",
  manifestNo: "İrsaliye no",
  dispatchNote: "Sevk notu",
  allocationCount: "Tahsis adedi",
  fromShipmentId: "Kaynak sevkiyat",
  returnedRolls: "İade edilen toplar",
  partialReturns: "Kısmi iadeler",
  removedRolls: "Çıkarılan toplar",
  removedSwatches: "Çıkarılan kartelalar",
  voidedDocs: "İptal edilen belgeler",
  docType: "Belge türü",
  documentProfileId: "Belge profili",
  copiedFrom: "Kopyalandığı kayıt",

  // ── Fason ──────────────────────────────────────────────────────────────────
  subcontractorId: "Fason firma",
  dispatchNo: "Sevk no",
  receiptNo: "Makbuz no",
  batchNumber: "Parti no",
  dispatched: "Sevk edildi",

  // ── Müşteri / cari ─────────────────────────────────────────────────────────
  address: "Adres",
  city: "İl",
  district: "İlçe",
  country: "Ülke",
  phone: "Telefon",
  contactName: "İlgili kişi",
  contactPhone: "İlgili kişi telefonu",
  email: "E-posta",
  taxNumber: "Vergi no",
  pendingReview: "İncelemeye düştü",

  // ── Kullanıcı / yetki / oturum ─────────────────────────────────────────────
  username: "Kullanıcı adı",
  fullName: "Ad soyad",
  passwordHash: "Parola",
  pin: "PIN",
  role: "Rol",
  permissions: "Yetkiler",
  permissionIds: "Yetkiler",
  permissionCode: "Yetki kodu",
  defaultPermissions: "Varsayılan yetkiler",
  codes: "Kodlar",
  grantedVia: "Veriliş yolu",
  validFrom: "Geçerlilik başlangıcı",
  validUntil: "Geçerlilik bitişi",
  replace: "Mevcutların yerine yazıldı",
  all: "Tümü",
  resetByAdmin: "Yönetici sıfırladı",
  endReason: "Bitiş sebebi",
  takenOverFromUserId: "Devralınan kullanıcı",
  byUserId: "İşlemi yapan",
  sessionStationId: "Oturum istasyonu",
  lastSeenAt: "Son görülme",
  started: "Başlatıldı",

  // ── Etiket / yazıcı / belge ────────────────────────────────────────────────
  language: "Yazıcı dili",
  languageOverride: "Yazıcı dili (ezme)",
  mode: "Mod",
  html: "Şablon içeriği",
  snapshot: "Belge içeriği",
  config: "Ayarlar",
  templateId: "Şablon",
  templateName: "Şablon adı",
  variantId: "Şablon varyantı",
  variantMatch: "Varyant eşleşmesi",
  elementsChanged: "Değişen öğeler",
  labelIntent: "Etiket amacı",
  labelWidthMm: "Etiket eni (mm)",
  labelHeightMm: "Etiket boyu (mm)",
  labelGapMm: "Etiket aralığı (mm)",
  labelDpi: "Yazıcı çözünürlüğü (dpi)",
  widthMm: "Genişlik (mm)",
  heightMm: "Yükseklik (mm)",
  mediaType: "Yazım türü",
  rasterMode: "Raster modu",
  scale: "Ölçek",
  qrScale: "Karekod ölçeği",
  standalone: "Bağımsız (kayıtsız)",
  rawCode: "Ham yazıcı kodu",
  lengthBanner: "Metraj bandı",
  wasDirty: "Bayat kopya idi",
  event: "Olay",

  // ── Cihaz / donanım ────────────────────────────────────────────────────────
  deviceId: "Cihaz",
  connectionType: "Bağlantı türü",
  readMode: "Okuma modu",
  port: "Port",
  host: "Sunucu",
  pollCommand: "Sorgu komutu",
  identifyPattern: "Tanıma deseni",
  terminator: "Satır sonu",
  timeoutMs: "Zaman aşımı (ms)",
  stationName: "İstasyon adı",
  machineName: "Makine adı",
  stationCapabilities: "İstasyon yetenekleri",
  previousStationId: "Önceki istasyon",
  originalStationId: "Asıl istasyon",
  stationRestored: "İstasyon geri yüklendi",
  stationRestoreNote: "İstasyon geri yükleme notu",
  previousMachineId: "Önceki makine",
  scannedOnMachineId: "Okutulduğu makine",

  // ── Sistem / yedek / içe aktarım ───────────────────────────────────────────
  env: "Ortam",
  nodeVersion: "Node sürümü",
  lanAddresses: "Yerel ağ adresleri",
  cutoff: "Kesim tarihi",
  cutoffSource: "Kesim tarihi kaynağı",
  trigger: "Tetikleyen",
  total: "Toplam",
  extraCount: "Fazladan kayıt",
  itemsAdded: "Eklenen kayıt",
  sourceId: "Kaynak kayıt",
  freedCode: "Serbest kalan kod",
  freedName: "Serbest kalan ad",
  lazyReconstruct: "Sonradan yeniden kuruldu",

  // ── Değeri ADA ÇÖZÜLEN alanlar (audit-value-resolver ile eşleşir) ──────────
  // Bu ikisi birlikte çalışır: harita UUID'yi ada çevirir, buradaki etiket alan
  // adını Türkçeleştirir. Biri eksikse satır yarı okunur kalır
  // ("workOrderId: İE1908260014") — bekçi ikisinin örtüşmesini denetler.
  plannedColorId: "Planlanan renk",
  customerBranchId: "Şube",
  stationId: "İstasyon",
  currentStationId: "Bulunduğu istasyon",
  entryStationId: "Giriş istasyonu",
  machineId: "Makine",
  createdMachineId: "Oluşturan makine",
  routeId: "Rota",
  propertyId: "Özellik",
  fabricPropertyId: "Özellik",
  valueId: "Özellik değeri",
  defectTypeId: "Hata tipi",
  returnReasonId: "İade sebebi",
  orderId: "Sipariş",
  workOrderId: "İş emri",
  batchId: "Parti",
  rollId: "Top",
  sackId: "Çuval",
  shipmentId: "Sevkiyat",
  userId: "Kullanıcı",
  operatorId: "Operatör",
  assignedToId: "Atanan kişi",
  printedById: "Basan kişi",
  // ── TİCARET / ÖN MUHASEBE ALANLARI (merge, 2026-09-01) ──────────────────────
  // Kaynak: `feature/depo-mal-kabul`. Ayna KURALI gereği backend ile Electron'a
  // AYNI satırlar yazılır (bekçi: `scripts/test_audit_labels.ts` §1).
  docNo: "Belge No",
  issueDate: "Belge Tarihi",
  transferNo: "Transfer No",
  countNo: "Sayım No",
  orderNo: "Sipariş No",
  cariId: "Cari Hesap",
  supplierId: "Tedarikçi",
  warehouseId: "Depo",
  exchangeRate: "Kur",
  vatRate: "KDV Oranı",
  netAmount: "Net Tutar",
  allocatedTotal: "Kapatılan Tutar",
  balanceKg: "Bakiye (kg)",
  qtyKg: "Miktar (kg)",
  // ── Üretim/kayıt alanları (aynı kaynaktan, sözlükte eksikti) ───────────────
  targetStatus: "Hedef Durum",
  endMeter: "Bitiş Metre",
  defectType: "Hata Tipi",
  severity: "Şiddet",
  actionTaken: "Alınan Aksiyon",
  isProcessed: "İşlendi",
  plateNumber: "Plaka",
  driverName: "Sürücü",
  categoryId: "Kategori",
  firstName: "Ad",
  lastName: "Soyad",
  permission: "Yetki",
  ipAddress: "IP Adresi",
  clientType: "İstemci",
};

/** Alanın Türkçe karşılığı; yoksa HAM AD (fail-open). */
export function auditFieldLabel(field: string): string {
  return AUDIT_FIELD_LABELS[field] ?? field;
}
