// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import path from "node:path";
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

// ⚠️ `.env` CWD'ye göre DEĞİL, bu dosyanın yanından okunur. Düz `dotenv/config`
// çalışma dizinine bakar: repo kökünden `npx prisma migrate deploy --config
// Teks-Erp/prisma.config.ts` koşulduğunda config yükleniyor ama kökte `.env`
// olmadığı için `DATABASE_URL` undefined kalıyor ve Prisma "The datasource.url
// property is required in your Prisma config file" ile düşüyordu — komut yanlış
// DB'ye gitmiyor, hiç çalışmıyordu. Diğer yollar (`schema`, `migrations.path`)
// Prisma tarafından zaten config dosyasına göre çözülüyor; eksik olan tek şey buydu.
loadEnv({ path: path.join(__dirname, ".env") });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx ts-node --project prisma/tsconfig.json prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
